### ISSUE TITLE
Update oidcrp.oauth2.__init__.py file import

### ISSUE THREAD

**Issue by s1q12** [openid/JWTConnect-Python-OidcRP#4]
Line 12 - from oidcservice.service import init_services

should be:
from oidcservice.service import build_services

**Comment by rohe** [comment]
Don't know why you say that.
build_services are not around anymore. Replaced by init_services.
Unfortunately example/conversation.py are not updated to reflect this.
And I have to updated the documentation.

**Comment by s1q12** [comment]
much appreciated for response.
I see my mistake.  I pip installed oidcservice, I see that the git repo oidcservice is updated.

**Comment by rohe** [comment]
A good point I should update PyPI.
