### ISSUE TITLE
missing dependency: CherryPy

### ISSUE THREAD

**Issue by MarcelPa** [openid/JWTConnect-Python-OidcRP#5]
I tried to use oidcrp in my code, it threw an ModuleNotFound error when using it. In `src/oidcrp/oauth2/__init__.py` CherryPy is imported, but the module is not stated in the requirements in the `setup.py`. Install cherrypy using pip resolves this error.
Adding cherrypy to the requirements in `setup.py` should resolve this issue.

**Comment by rohe** [comment]
I'd rather remove the dependency on cherrypy from `src/oidcrp/oauth2/__init__.py`.
Let me work on it.
It seems stupid to have a dependency on cherrypy if you've chosen to work with flask :-/

**Comment by MarcelPa** [comment]
It looks like CherryPy is exclusively used to raise appropriate errors (an idea I really like by the way). In the flask world, you could possibly find a suitable replacement from Werkzeug:

https://werkzeug.palletsprojects.com/en/0.15.x/exceptions/#werkzeug.exceptions.HTTPException

**Comment by peppelinux** [comment]
I'd like to have this library decoupled by any wsgi/http implementation, cherry and wekzeug or others.
A simple Custom and self-explanatory Exception could do the work.

when I'll use it in Django I'll import the custom exceptions to handle them in my implementation.

**Comment by rohe** [comment]
To have it decoupled was something we aimed for. At the same time there MUST be a default that is easily usable.

I think I've change the Exceptions in the last update.

**Comment by peppelinux** [comment]
this could be closed, dependency was removed
