### ISSUE TITLE
typo in the docs regarding configuration parameters

### ISSUE THREAD

**Issue by MarcelPa** [openid/JWTConnect-Python-OidcRP#6]
There is a type in the readthedocs documentation regarding the configuration parameters.
It states that `client_prefs` is the configuration key used to specify "How the RP should prefer to behave against the OP/AS", wheras it should be `client_preferences`.
This is just a minor detail, but it kept me quite some time to figure out this typo. 

I am talking about `doc/source/rp_handler.rst` on line 312.

If you like, I can open a PR for that.

**Comment by rohe** [comment]
Please do !
Thanks !
